hist(regressionstats$mape*100,xlab="Mean Absolute Percentage Error",main="")
abline(v=8.9,col="red",lty=2,lwd=2)
mtext(side=3,line=-4,adj=.3,"Median Value 8.9%",col="red")

dat2 = regressionstats %>% left_join(select(EcoContext,WiscID,lat,long))
rbPal <- colorRampPalette(c('red','green','blue','orange'))
dat2$Col <- rbPal(11)[as.numeric(cut(dat2$slope,breaks = as.numeric(quantile(dat2$slope,probs=seq(0,1,.1)))))]
legend.val <-rbPal(11)
legend.lab = round(as.numeric(quantile(dat2$slope,probs=seq(0,1,.1))),2)
map.regions = c('wisconsin')
options(device="quartz")
dev.new(width=7,height=6)
par(mar=c(5.1,4.1,4.1,2.1))
map('state',region=map.regions,col=grey(.98),fill=TRUE,resolution = 0,mar=c(0,0,0,0),border=grey(.5),lty=5)
points(dat2$long,dat2$lat,col=alpha(dat2$Col,1),pch=16)
# legend("topright",legend=c("Gnet -2.70 mm/d","Gnet 0.150 mm/d"),pch=16,col=c("#FF0000","#0000FF"),title = "Net Groundwater Discharge",bty="n")       
legend.col(col = legend.val, lev = 0:10,lab=legend.lab,at=0:10)
graphics.off()
plot(anvillake$date,anvillake$obs_waterlevel_mm,type="b",col=alpha(1,.7),pch=16,cex=1,xlab="Date",ylab="Water Level (mm)",main="Anvil Lake")
points(anvillake$date,anvillake$modeled_waterlevel_mm,type="b",col=alpha(4,.7),pch=16,cex=1)
legend("topright",legend=c("Observed","Modeled"),col=c(alpha(1,.7),alpha(4,.7)),pch=16,lty=1,cex=0.8)
